spring.application.name=api-gateway

server.port=9000


# ==============================
# COURSE SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[0].id=course-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:9002
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/courses/**


# ==============================
# ENROLLMENT SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[1].id=enrollment-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:9003
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/enrollments/**


# ==============================
# PAYMENT SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[2].id=payment-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:9004
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/payments/**


# ==============================
# AUTH SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[3].id=auth-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:9005
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/auth/**


# CORS

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5178
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*